version: '2'
services:
  jhipster6-app:
    image: jhipster6
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipster6-postgresql:5432/jhipster6
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipster6-postgresql:
    extends:
      file: postgresql.yml
      service: jhipster6-postgresql
