name: Jhipster 6
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches-ignore:
      - master
  pull_request:
jobs:
    pipeline:
        name: jhipster6 pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
        timeout-minutes: 40
        env:
            NODE_VERSION: 12.13.1
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v1
            - uses: ./.github/actions/action
